# Generated by Django 4.2.27 on 2026-02-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_comeplete_by_todo_complete_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complete_by',
            field=models.DateField(),
        ),
    ]
