# Generated by Django 4.2.27 on 2026-02-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_complete_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complete_by',
            field=models.DateField(blank=True, null=True),
        ),
    ]
